### ISSUE TITLE
Spotify API credentials not setup.

### ISSUE THREAD

**Issue by checkso** [LaurenceRawlings/savify#16]
* Savify version: 2.0.10
* Python version: 3.9.1
* Operating System: Windows 10

### Description

Trying to use Savify to download a playlist, but receiving error message below. Downloaded latest savify.exe file and did not configure a API.

### What I Did

```
**Command:**
savify "SPOTIFY URL"

Tried several different URLs, all the same error

**Traceback:**
Traceback (most recent call last):
  File "savify\__main__.py", line 11, in <module>
  File "savify\__init__.py", line 24, in cli
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "savify\cli.py", line 57, in main
  File "savify\savify.py", line 46, in __init__
RuntimeError: Spotify API credentials not setup.
[12308] Failed to execute script __main__
```

Isn't the idea of the .exe file to not setup the Spotify URL?

**Comment by inacio0196** [comment]
I had the same problem on ubuntu 20.04 LTS

**Comment by LaurenceRawlings** [comment]
The executable is just a packaged version o the python CLI, it's for people that don't want to download python. Later down the line a GUI will be released which won't need API credentials to be configured.
