### ISSUE TITLE
[BUG] unable to download due to youtube-dl error

### ISSUE THREAD

**Issue by JellyZhang** [LaurenceRawlings/savify#59]
** what happended**
```
[INFO]  Downloading 1 songs...
[ERROR] ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/extractor/youtube.py", line 1303, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/extractor/youtube.py", line 1204, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/extractor/youtube.py", line 1279, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[ERROR] ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/extractor/youtube.py", line 1303, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/extractor/youtube.py", line 1204, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/extractor/youtube.py", line 1279, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[ERROR] ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/extractor/youtube.py", line 1303, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/extractor/youtube.py", line 1204, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/extractor/youtube.py", line 1279, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
**To Reproduce**

```
docker run --rm -v "`pwd`:/root/.local/share/Savify/downloads" \
           -e SPOTIPY_CLIENT_ID=xxxxxx \
           -e SPOTIPY_CLIENT_SECRET=xxxx \
           laurencerawlings/savify:latest "https://open.spotify.com/track/4Dju9g4NCz0LDxwcjonSvI"
```

**Expected behavior**
no errors.

**Desktop (please complete the following information):**
 - OS: macos
 - Version 2.3.4
 - youtube-dl version: 2021.06.06
 - ffmpeg version: 4.4.1

**Comment by n3myy** [comment]
Had the same issue. There is a pull request with a fix. Essentially replacing youtube-dl module with yt-dlp.

**Comment by lumixdeee** [comment]
I'm getting a very similar problem, Could not find JS function 'na' (instead of 'sa').

Verbose:
youtube-dl --verbose --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=ugxQPwXhwJA 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--extract-audio', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=ugxQPwXhwJA']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.2 (CPython) - Linux-5.18.0-0.deb11.4-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ugxQPwXhwJA: Downloading webpage
[youtube] ugxQPwXhwJA: Downloading player dac945fd
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'sa'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'sa'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'sa'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'sa'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1623, in _real_extract
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1358, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'sa'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'sa'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by StefCoders** [comment]
Same thing.
