### ISSUE TITLE
[BUG] Cannot download songs with a "." in it.

### ISSUE THREAD

**Issue by StefCoders** [LaurenceRawlings/savify#86]
**Describe the bug**

My song, Fred Again.., cannot be downloaded as it contains a dot.

**To Reproduce**
Steps to reproduce the behavior [e.g. the command you ran]:

Download a song with a dot in it.

**Expected behavior**

Download the song with no problems.

**Screenshots**

```
Traceback (most recent call last):
  File "pathlib.py", line 1312, in mkdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\stefa\\AppData\\Roaming\\Savify\\downloads\\Fred again..\\Baby again..'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "savify\__main__.py", line 11, in <module>
  File "savify\__init__.py", line 25, in cli
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "savify\cli.py", line 110, in main
  File "savify\savify.py", line 109, in download
  File "multiprocessing\pool.py", line 364, in map
  File "multiprocessing\pool.py", line 771, in get
  File "multiprocessing\pool.py", line 125, in worker
  File "multiprocessing\pool.py", line 48, in mapstar
  File "savify\savify.py", line 148, in _download
  File "savify\utils.py", line 21, in create_dir
  File "pathlib.py", line 1317, in mkdir
  File "pathlib.py", line 1312, in mkdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\stefa\\AppData\\Roaming\\Savify\\downloads\\Fred again..\\Baby again..'
[13364] Failed to execute script __main__
```

**Desktop (please complete the following information):**
 - OS: [e.g. windows, ubuntu]
 - Version [2.0,1]

**Additional context**

**Comment by StefCoders** [comment]
Idea: Maybe rename songs with dots in them to remove the dots.
