### ISSUE TITLE
[BUG] Downloading works but i got this errors in log

### ISSUE THREAD

**Issue by kuvvat** [LaurenceRawlings/savify#88]
youtube_dl.utils.ExtractorError: Could not find JS function 'ya'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'ya'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[ERROR]	ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/extractor/youtube.py", line 1303, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/extractor/youtube.py", line 1204, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/extractor/youtube.py", line 1279, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl-2021.1.24.1-py3.8.egg/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ya'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'ya'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by NXTDMNSN** [comment]
Unfortunately, YT-DL has been issued a DMCA takedown and their servers have been shut down by the German Government :D

https://openjur.de/u/2466945.html
